export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USER_CREATING_START = 'USER_CREATING_START';
export const USER_CREATING_SUCCESS = 'USER_CREATING_SUCCESS';
export const USER_CREATING_FAIL = 'USER_CREATING_FAIL';

export const FETCH_USERS_SUCCESS ='FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const USER_SWIPED_DIRECTION = 'USER_SWIPED_DIRECTION';

export const FETCH_MATCHES_START = 'FETCH_MATCHES_START';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_FAIL = 'FETCH_MATCHES_FAIL';

export const FETCH_MESSAGES_START ='FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS ='FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL ='FETCH_MESSAGES_FAIL';
export const SEND_MESSAGE_START ='SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS ='SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL ='SEND_MESSAGE_FAIL';

//export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';