export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USER_CREATING_START = 'USER_CREATING_START';
export const USER_CREATING_SUCCESS = 'USER_CREATING_SUCCESS';
export const USER_CREATING_FAIL = 'USER_CREATING_FAIL';

//export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';